import { Bar } from '@/components/bar'
import { Post } from '@/components/post'
import styles from '@/styles/Home.module.scss'
import Head from 'next/head'
import Anne from '../assets/image-anne.jpg'
import Colton from '../assets/image-colton.jpg'
import Irene from '../assets/image-irene.jpg'

export default function Home() {

  const Texts = ["Rated 5 Stars in Reviews","Rated 5 Stars in Report Guru","Rated 5 Stars in BestTech"]
  const Peoples = [{
    image: Colton,
    name: 'Colton Smith',
    description: `" We needed the same printed design as the one we had ordered a week prior. Not only did they find the original order, but we also receibed it in time. Excellent! "`
  },{
    image: Irene,
    name: 'Irene Roberts',
    description: `" Customer service is always excellent and very quick turn around. Completely delighted with the simplicity of the purchase and the speed of delivery"` 
  },
  {
    image: Anne,
    name: 'Anne Wallace',
    description: `" Put an order with this company and can only praise them for the very high standard. Will definitely use them again and recommend them to everyone "` 
  }
]

  return (
    <>
      <Head>
        <title>Social proof section</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon-32x32.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=League+Spartan:wght@400;500;700&display=swap" rel="stylesheet"/>
      </Head>
      <main className={styles.main}>
        <div className={styles.containerTop}>
          <div className={styles.containerTopLeft}>
            <h1>10,000+ of our users love our products.</h1>
            <p>We only provide great products combined with excellent customer service. See what out satisfied customers are saying about our services.</p>
          </div>
          <div className={styles.containerTopRight}>
            {Texts.map((text,index)=>{
              return <Bar left={100*index} text={text}/>
            })}
          </div>
        </div>

        <div className={styles.containerBottom}>
          {Peoples.map((element, index)=>{
             return (<Post name={element.name} top={13 * index} image={element.image} description={element.description}  />)
          })}
        </div>
          
      </main>
    </>
  )
}
